# ====================================
# Economy Plugin Configuration
# ====================================

# Версия конфига (не изменяйте!)
config_version: "1.0"

# ====================================
# НАСТРОЙКИ БАЗЫ ДАННЫХ
# ====================================
database:
  # Тип базы данных: sqlite или mysql
  type: "sqlite"

  # Настройки MySQL (если type: mysql)
  host: "localhost"
  port: 3306
  database: "economy"
  username: "root"
  password: ""

  # Настройки пула соединений
  pool:
    maximum_pool_size: 10
    minimum_idle: 2
    connection_timeout: 30000
    idle_timeout: 600000
    max_lifetime: 1800000

# ====================================
# НАСТРОЙКИ MEDIEVAL FACTIONS
# ====================================
medieval_factions:
  # Включить интеграцию с Medieval Factions
  enabled: true

  # Настройки базы данных Medieval Factions
  database:
    # Тип базы данных MF (h2, sqlite, mysql)
    type: "h2"

    # URL подключения к H2 (из конфига MF)
    url: "jdbc:h2:./medieval_factions_db;AUTO_SERVER=true;MODE=MYSQL;DATABASE_TO_UPPER=false"

    # Диалект базы данных
    dialect: "H2"

    # Логин и пароль
    username: "sa"
    password: ""

    # Альтернативные настройки для других типов БД
    sqlite:
      path: "plugins/MedievalFactions/database.db"

    mysql:
      host: "localhost"
      port: 3306
      database: "medievalfactions"
      username: "root"
      password: ""

  # Право на управление валютой
  currency_permission: "CURRENCY_MANAGE"

  # Разрешить создание валют без фракции (для тестирования)
  allow_without_faction: true

# ====================================
# НАСТРОЙКИ ВАЛЮТ
# ====================================
currencies:
  # Стартовый баланс VIL для новых игроков
  starting_vil_balance: 100

  # Требования к названию валют
  name_requirements:
    # Длина названия валюты (только 3 символа)
    length: 3
    # Только заглавные латинские буквы
    pattern: "^[A-Z]{3}$"

  # Зарезервированные названия валют (нельзя создать)
  reserved:
    - "VIL"  # Системная валюта
    - "USD"  # Доллар США
    - "EUR"  # Евро
    - "RUB"  # Российский рубль
    - "GBP"  # Британский фунт
    - "JPY"  # Японская йена
    - "CHF"  # Швейцарский франк
    - "CAD"  # Канадский доллар
    - "AUD"  # Австралийский доллар
    - "CNY"  # Китайский юань
    - "KRW"  # Южнокорейская вона
    - "INR"  # Индийская рупия
    - "BRL"  # Бразильский реал
    - "MXN"  # Мексиканское песо
    - "ZAR"  # Южноафриканский рэнд

  # Разрешенные примеры валют
  allowed_examples:
    - "ABC"
    - "XYZ"
    - "FOO"
    - "BAR"
    - "DEF"
    - "GHI"
    - "JKL"
    - "MNO"
    - "PQR"
    - "STU"

# ====================================
# НАСТРОЙКИ ЭМИССИИ
# ====================================
emission:
  # Максимальная эмиссия по умолчанию для новых валют
  default_max_emission: 1000000000

  # Минимальная эмиссия
  min_emission: 1000

  # Максимальная эмиссия
  max_emission: 2000000000

  # Лимиты эмиссии для системных валют
  system_limits:
    VIL: 2000000000

# ====================================
# НАСТРОЙКИ КОШЕЛЬКА
# ====================================
wallet:
  # Количество валют на одной странице
  currencies_per_page: 10

  # Максимальное количество валют в кошельке
  max_currencies: 50

  # Автосохранение кошельков (в секундах)
  auto_save_interval: 300

# ====================================
# НАСТРОЙКИ АУКЦИОНА
# ====================================
auction:
  # Время жизни лота в часах
  expiration_hours: 72

  # Максимальное количество предметов на аукционе на игрока
  max_items_per_player: 10

  # Минимальная цена предмета
  min_price: 1

  # Максимальная цена предмета
  max_price: 1000000000

  # Настройки прав для лимитов предметов
  permissions:
    # Неограниченное количество предметов
    unlimited: "economy.auction.max.unlimited"
    # VIP лимит (50 предметов)
    vip: "economy.auction.max.50"
    # Премиум лимит (25 предметов)
    premium: "economy.auction.max.25"
    # Обычный лимит (10 предметов)
    normal: "economy.auction.max.10"

  # Лимиты по группам (если права не работают)
  limits:
    default: 10
    vip: 50
    premium: 25
    admin: 999
    op: 999

  # Настройки GUI
  gui:
    size: 54
    titles:
      main: "&6§lАУКЦИОН"
      currency_selection: "&6Аукцион - {currency}"
      items: "&6Предметы - {category}"
      expired: "&cИстекшие предметы"
      active: "&aАктивные лоты"
      premium: "&6⭐ ПРЕМИУМ МАГАЗИН ⭐"

  # Категории предметов
  categories:
    BUILDING_BLOCKS:
      name: "&6Блоки"
      icon: "BRICKS"
      description: "Строительные блоки"

    DECORATIONS:
      name: "&5Декорации"
      icon: "PAINTING"
      description: "Декоративные предметы"

    REDSTONE:
      name: "&cРедстоун"
      icon: "REDSTONE"
      description: "Редстоун механизмы"

    TRANSPORTATION:
      name: "&9Транспорт"
      icon: "MINECART"
      description: "Транспортные средства"

    MISCELLANEOUS:
      name: "&7Разное"
      icon: "LAVA_BUCKET"
      description: "Прочие предметы"

    FOOD:
      name: "&aЕда"
      icon: "APPLE"
      description: "Продукты питания"

    TOOLS:
      name: "&eИнструменты"
      icon: "DIAMOND_PICKAXE"
      description: "Инструменты и утилиты"

    COMBAT:
      name: "&4Оружие"
      icon: "DIAMOND_SWORD"
      description: "Боевые предметы"

    BREWING:
      name: "&dЗелья"
      icon: "BREWING_STAND"
      description: "Зелья и ингредиенты"

# ====================================
# НАСТРОЙКИ БИРЖИ
# ====================================
bourse:
  # Максимальное количество ордеров на игрока по умолчанию
  default_max_orders: 3

  # Минимальная сумма ордера
  min_order_amount: 1

  # Максимальная сумма ордера
  max_order_amount: 1000000000

  # Комиссия биржи (в процентах)
  commission_rate: 0.01

  # Настройки прав для лимитов ордеров
  permissions:
    # Неограниченное количество ордеров
    unlimited: "economy.bourse.max.unlimited"
    # VIP лимит (20 ордеров)
    vip: "economy.bourse.max.20"
    # Премиум лимит (15 ордеров)
    premium: "economy.bourse.max.15"
    # Обычный лимит (5 ордеров)
    normal: "economy.bourse.max.5"

  # Лимиты по группам
  limits:
    default: 3
    vip: 20
    premium: 15
    admin: 999
    op: 999

  # Настройки GUI
  gui:
    size: 54
    titles:
      main: "&6Биржа валют"
      trading_pair: "&6{sell_currency} → {buy_currency}"
      my_orders: "&6Мои ордера"
      popular_pairs: "&6Популярные пары"

# ====================================
# НАСТРОЙКИ ПРЕМИУМ МАГАЗИНА
# ====================================
premium_shop:
  enabled: true

  # Валюта премиум магазина
  currency: "VIL"

  # Настройки GUI
  gui:
    size: 54
    title: "&6⭐ ПРЕМИУМ МАГАЗИН ⭐"

  # Автообновление магазина
  auto_refresh: true
  refresh_interval: 3600  # в секундах

# ====================================
# ЛИМИТЫ СИСТЕМЫ
# ====================================
limits:
  # Максимальная сумма перевода за раз
  max_transfer_amount: 1000000000

  # Максимальное количество транзакций в день
  max_transactions_per_day: 100

  # Максимальное количество валют на сервере
  max_currencies: 50

  # Максимальное количество фракций
  max_factions: 100

# ====================================
# НАСТРОЙКИ ИНТЕГРАЦИИ
# ====================================
integration:
  # PlaceholderAPI
  placeholderapi:
    enabled: true

  # Vault
  vault:
    enabled: false
    hook_vil_as_main_currency: true

# ====================================
# СООБЩЕНИЯ
# ====================================
messages:
  prefix: "&6[Economy] &r"

  # Общие сообщения
  no_permission: "&cУ вас нет прав!"
  player_not_found: "&cИгрок не найден!"
  invalid_amount: "&cНеверная сумма!"
  invalid_currency: "&cНеверная валюта!"
  database_loading: "&eБаза данных загружается, попробуйте позже..."
  command_usage: "&cИспользование: {usage}"

  # Сообщения валют
  currency:
    created: "&aВалюта {currency} создана успешно!"
    exists: "&cТакая валюта уже существует!"
    invalid_name: "&cНеверное название валюты!"
    reserved_currency: "&cЭта валюта зарезервирована!"
    wrong_length: "&cНазвание валюты должно содержать ровно 3 символа!"
    only_latin_uppercase: "&cИспользуйте только заглавные латинские буквы!"
    name_requirements: "&7Требования: 3 заглавные латинские буквы"
    reserved_list: "&7Зарезервированные: VIL, USD, EUR, RUB, GBP, JPY, CHF, CAD, AUD"
    allowed_examples: "&aПримеры разрешенных валют: ABC, XYZ, FOO, BAR, DEF"
    faction_already_has_currency: "&cВаша фракция уже имеет валюту!"
    no_faction: "&cВы должны состоять во фракции для создания валюты!"
    no_faction_permission: "&cУ вас нет прав на создание валюты во фракции!"
    mf_not_found: "&cMedieval Factions не найден!"
    mf_database_error: "&cОшибка подключения к базе данных Medieval Factions!"

  # Сообщения кошелька
  wallet:
    empty: "&7Ваш кошелек пуст"
    page_header: "&6=== Кошелек игрока {player} (страница {page}/{total}) ==="
    vil_balance: "&6⭐ VIL: &e{amount} &7(Премиум валюта)"
    currency_balance: "&7{currency}: &f{amount}"
    total_currencies: "&7Всего валют: &f{count}"
    invalid_page: "&cСтраница {page} не существует!"
    navigation_hint: "&7Используйте &f/wallet {page} &7для перехода"

  # Сообщения переводов
  transfer:
    success: "&aПеревод выполнен успешно!"
    sent: "&aВы отправили {amount} {currency} игроку {player}"
    received: "&aВы получили {amount} {currency} от игрока {player}"
    not_enough_money: "&cНедостаточно средств!"
    cannot_send_to_self: "&cВы не можете отправить деньги самому себе!"
    amount_too_large: "&cСлишком большая сумма!"

  # Сообщения аукциона
  auction:
    no_items: "&7На аукционе пока нет предметов"
    items_found: "&7Найдено предметов: {count}"
    item_bought: "&aВы купили предмет за {price} {currency}!"
    item_sold: "&aВаш предмет продан за {price} {currency}!"
    item_expired: "&cВремя продажи предмета истекло"
    item_returned: "&aПредмет возвращен в ваш инвентарь!"
    max_items_reached: "&cВы достигли лимита предметов на аукционе! ({max})"
    item_listed: "&aПредмет выставлен на аукцион за {price} {currency}!"
    item_cancelled: "&aЛот отменен и предмет возвращен!"
    take_item_in_hand: "&cВозьмите предмет в руку!"
    invalid_price: "&cЦена должна быть больше 0!"
    cannot_buy_own_item: "&cВы не можете купить свой предмет!"
    item_already_sold: "&cПредмет уже продан!"
    no_active_items: "&7У вас нет активных лотов"
    no_expired_items: "&7У вас нет истекших предметов"

  # Сообщения биржи
  bourse:
    order_created: "&aОрдер создан успешно! ID: #{id}"
    order_cancelled: "&aОрдер #{id} отменен!"
    order_executed: "&aОрдер #{id} исполнен!"
    order_not_found: "&cОрдер не найден!"
    max_orders_reached: "&cВы достигли лимита ордеров! ({max})"
    insufficient_funds: "&cНедостаточно средств для создания ордера!"
    same_currency: "&cНельзя обменивать валюту на саму себя!"
    invalid_order_id: "&cНеверный ID ордера!"
    cannot_buy_own_order: "&cВы не можете купить свой собственный ордер!"
    no_orders: "&7У вас нет активных ордеров"
    order_partially_filled: "&aОрдер #{id} частично исполнен!"
    no_popular_pairs: "&7Популярных пар пока нет"
    usage_hint: "&7Создавайте ордера для обмена валют"

  # Сообщения эмиссии
  emission:
    success: "&aУспешно выпущено {amount} {currency}!"
    no_permission: "&cУ вас нет прав на управление валютой {currency}!"
    limit_exceeded: "&cПревышен лимит эмиссии! Доступно: {available}"
    current_emission: "&7Текущая эмиссия: &f{current}"
    max_emission: "&7Максимальная эмиссия: &f{max}"
    available_emission: "&7Доступно для выпуска: &f{available}"
    invalid_amount: "&cНеверное количество для эмиссии!"

  # Сообщения премиум магазина
  premium:
    item_purchased: "&a⭐ Предмет куплен за {price} VIL! ⭐"
    insufficient_vil: "&cНедостаточно VIL! Нужно: {price}"
    item_out_of_stock: "&cПредмет закончился!"
    shop_empty: "&7Премиум магазин пуст"

# ====================================
# НАСТРОЙКИ ПРОИЗВОДИТЕЛЬНОСТИ
# ====================================
performance:
  # Использовать асинхронные операции
  async_database: true

  # Интервал автосохранения (в секундах)
  auto_save_interval: 300

  # Размер кэша кошельков
  wallet_cache_size: 1000

  # Время жизни кэша (в секундах)
  cache_expire_time: 600

  # Пакетная обработка транзакций
  batch_transactions: true
  batch_size: 100

  # Размер пула соединений с БД
  database_pool_size: 10

# ====================================
# НАСТРОЙКИ ОЧИСТКИ
# ====================================
cleanup:
  # Автоматическая очистка
  auto_cleanup: true

  # Интервал очистки (в минутах)
  cleanup_interval: 60

  # Количество дней для хранения транзакций
  transaction_days_to_keep: 30

  # Очистка истекших аукционов
  auto_cleanup_expired_auctions: true

  # Очистка пустых кошельков
  cleanup_empty_wallets: false

# ====================================
# НАСТРОЙКИ ОТЛАДКИ
# ====================================
debug:
  enabled: false
  log_transactions: true
  log_database_queries: false
  log_wallet_operations: false
  verbose_logging: false

# ====================================
# НАСТРОЙКИ БЕЗОПАСНОСТИ
# ====================================
security:
  # Максимальное количество попыток операций в минуту
  rate_limit: 60

  # Блокировка подозрительных операций
  fraud_detection: true

  # Логирование всех операций
  audit_log: true

  # Проверка целостности данных
  data_integrity_check: true

# ====================================
# ЭКСПЕРИМЕНТАЛЬНЫЕ ФУНКЦИИ
# ====================================
experimental:
  # Новый алгоритм кэширования
  advanced_caching: false

  # Оптимизация базы данных
  database_optimization: false

  # Предварительная загрузка данных
  data_preloading: false

# ====================================
# НАСТРОЙКИ УВЕДОМЛЕНИЙ
# ====================================
notifications:
  # Уведомления о переводах
  transfer_notifications: true

  # Уведомления о продажах на аукционе
  auction_notifications: true

  # Уведомления об исполнении ордеров
  bourse_notifications: true

  # Звуковые уведомления
  sound_notifications: true
  sounds:
    money_received: "ENTITY_EXPERIENCE_ORB_PICKUP"
    item_sold: "ENTITY_VILLAGER_YES"
    order_executed: "BLOCK_NOTE_BLOCK_PLING"

# ====================================
# НАСТРОЙКИ ЛОКАЛИЗАЦИИ
# ====================================
localization:
  # Язык по умолчанию
  default_language: "ru"

  # Формат чисел
  number_format: "#,###"

  # Формат даты и времени
  date_format: "dd.MM.yyyy HH:mm"

  # Часовой пояс
  timezone: "Europe/Moscow"

# Не изменяйте эту строку!
version: "${project.version}"